### PR TITLE
Child studies field

### PR DESCRIPTION
**Pull request by reynoldtan**
This PR will create a Tripal 3 field that will show a summary of traits with corresponding stocks and experiments a trait was measured, organized in cards/tiles. Each tile is titled with the trait name and elements underneath are the stock, followed by the experiment as one unit of information a trait was used in.

Screen Shot 2019-10-02 at 9 57 40 AM (2)

Features:
1. Trait links to trait profile page.
2. Stock name links to stock profile page.
3. Colour codes to easily compare similar stock names.
4. Stock group select - will select same traits across all tiles when pointing to a stock.

## Metadata

 - Issue https://github.com/UofS-Pulse-Binfo/analyzedphenotypes/issues/104 Stock Child Studies

- [X] I feel this PR is ready to be merged.
- [X] This PR is dependent upon [PR #/ nothing]
  No dependencies

Documentation:
- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

## Testing?
1. Update AP to include this new field.
2. Add field ideally to a Registered Variety.
3. Load a germplasm of type #2. This germ must contain an alternative (is_selection_of)
germplasm that has phenotypes associated to it.

- [ ] I tested on a generic Tripal Site
- [X] I tested on a KnowPulse Clone
- [ ] This PR includes automated testing

### CODE REVIEW

**Review by laceysanderson — COMMENTED** [review]
I've set up my KnowPulse clone according to the instructions with the child studies field on the registered cultivar content type, ensured it is not disabled in the display, turned off `Hide empty fields` and cleared the cache many times. However I cannot get this field to show up. My example page was `CDC Glamis` and I confirmed the expected relationship was present:
Screen Shot 2019-10-30 at 4 39 07 PM

**Comment by reynoldtan** [comment]
I tried the child studies in my old AP, no child studies, setup the field as you described and got this result.

Screen Shot 2019-11-06 at 10 44 24 AM (2)

Could you please check if that CDC Glamis has 
1. Has no phenotype associated to it.
2. Has other related stock where the relationship is is_selection_of (ie. CDC Glamis AGL).

**Comment by laceysanderson** [comment]
I did confirm the above and was able to replicate the problem on staging. I did a little debugging and determined the results from `load()` were not being formatted properly in some cases. The latest commit fixes it.

**Review by laceysanderson — CHANGES_REQUESTED** [review]
This list is likely going to get really long... perhaps we should add hide functionality like we did in our other trait summary field:
Screen Shot 2019-11-13 at 9 38 58 AM

**Comment by reynoldtan** [comment]
Screen Shot 2019-11-20 at 1 29 47 PM

Hide/Reveal button to show less or more phenotypes.

**Review by laceysanderson — APPROVED** [review]
Works perfectly!

**Pull request merged**
