### PR TITLE
Input File now requires method name and unit.

### PR DESCRIPTION
**Pull request by laceysanderson**
## Metadata

 - Issue #59 

- [x] I feel this PR is ready to be merged.
- [ ] This PR is dependent upon [PR #/ nothing]

Documentation:
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

## Description
Since the upload file format only has a column for trait name, if the same trait is in the file with multiple measurements, they will be combined. For example, if we have a time course for canopy height (same trait, multiple methods) then the describe form will only show a single fieldset for canopy height and you will only be able to specify a single method.

Solution: add unique short measurement name and unit to file format and autofill fields based on them.

## Testing?

- [x] I tested on a generic Tripal Site
- [x] I tested on a KnowPulse Clone
- [x] This PR includes automated testing

To test this PR, try uploading files with more then one method per trait. When done you should see both methods listed under the same trait in the trait distribution plot selection form.

Things to keep an eye on:
- check file validation (germplasm index changed)
- check summary statistics in describe stage
- now the method description and unit should be filled in automatically if the trait was already saved with the same method (no more markup with lists to copy/paste from)
- you should not be able to change the unit, method or trait name.

### CODE REVIEW

**Comment by reynoldtan** [comment]
No autofill value in Collection Method Description when using an existing Method Name. Name, Trait Description, Name and other field have value.

screen shot 2019-02-19 at 10 22 12 am


Other than this, all worked 👍.

**Comment by laceysanderson** [comment]
There, I was able to duplicate the problem and feel I have fixed it. Can you double check @reynoldtan?

**Comment by laceysanderson** [comment]
Merge conflicts fixed. Make sure to clear the cache before re-testing this as a previous PR moved directories a bit.

**Comment by reynoldtan** [comment]
Works 👍 , my collection method description now has autofill value. @laceysanderson did you intend the field to be disabled like the rest of the fields? It is enabled on my test shown below. 
screen shot 2019-02-20 at 11 19 59 am 2

**Comment by laceysanderson** [comment]
Good call, it's disabled now when it's autofilled.

**Pull request merged**
