### PR TITLE
Phenotype summary fields

### PR DESCRIPTION
**Pull request by reynoldtan**
This PR will create Tripal 3 fields for showing phenotypic data summaries.

## Metadata

 - Issue  https://github.com/UofS-Pulse-Binfo/analyzedphenotypes/issues/81
Phenotype Summary Fields

- [X] I feel this PR is ready to be merged.
- [ ] This PR is dependent upon [PR #/ nothing]

Documentation:
- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

## Dependencies

none

## Testing?

Screen Shot 2019-05-09 at 3 09 38 PM (2)

This PR contains a set of Tripal 3 fields where some fields are compatible for both germplasm page and trait page while others are aimed at either pages. For fields: 

- Number of experiments
- Number of years
- Number of locations

Add these fields to Germplasm and/or Traits content types. Whereas 
- Number of Germplasm 
- Number of Values Recorded

are exclusive to Traits. Lastly,

- Number of Traits

field goes to Germplasm page only.

When available, a variable to show more detailed count can be set to show items the count is based on, that can be used as an alternative display option, or to verify result and for debugging purposes.

ie: `$detailed = TRUE;`

- [X] I tested on a generic Tripal Site
- [ ] I tested on a KnowPulse Clone
- [ ] This PR includes automated testing

### CODE REVIEW

**Review by laceysanderson — CHANGES_REQUESTED** [review]
You should optimize the performance of these queries. I would use as few joins as possible. Also, some of these pull the whole resultset into memory and then count using php... this should be changed to counting in postgresql so we don't even up using too much RAM.

**Comment by reynoldtan** [comment]
I dropped detailed display option that made the queries heavy. Setup option to embed infographics/image to be used when rendering a field type using the phenotype summary formatter.

**Review by laceysanderson — CHANGES_REQUESTED** [review]
In `hook_bundle_fields_info()` your fields are only instantiated for traits; whereas, they should also be for germplasm where applicable. Also, they need to be added to `hook_bundle_instances_info` so that they auto-attach to the content types.

**Review by laceysanderson — APPROVED** [review]
Works 👍 
Screen Shot 2019-06-18 at 2 41 20 PM
Screen Shot 2019-06-18 at 2 42 55 PM

**Pull request merged**
