### PR TITLE
74 download fix

### PR DESCRIPTION
**Pull request by reynoldtan**
This PR will fix average rep issue where related rows (related by experiment, germplasm, year and location) are not merged into a single row.

Screen Shot 2019-03-27 at 9 27 09 AM
Image shows averaged across replicate but listing 2 rows instead of one row for the same experiment, germplasm, year and location.

This PR also disabled Max missing data field option since this is currently not implemented and field does not have any effect on the exported file.
Screen Shot 2019-03-27 at 10 56 30 AM

## Metadata

 - Issue # https://github.com/UofS-Pulse-Binfo/analyzedphenotypes/issues/74
Download not combining rows for a single exp/loc/rep/yr/germplasm

- [X] I feel this PR is ready to be merged.
- [ ] This PR is dependent upon [PR #/ nothing]

Documentation:
- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

## Testing?

Simply download data and select multiple traits and germplasm. Make sure to check off 
Screen Shot 2019-03-27 at 10 58 33 AM

Take note of the options selected and repeat the process except this time uncheck Average Replicate option to export all records then compare both results
Screen Shot 2019-03-27 at 11 10 39 AM
.

Tip:
To easily see data in rows and column, set the file type to XLSX - excel.

- [x] I tested on a generic Tripal Site
- [x] I tested on a KnowPulse Clone
- [ ] This PR includes automated testing

### CODE REVIEW

**Review by laceysanderson — CHANGES_REQUESTED** [review]
This PR fixes the problem when "Average Replicates per site-year" is selected. However, the problem still exists when "Average Replicates per site-year" is __not__ selected.

Screen Shot 2019-04-12 at 2 23 39 PM
Above, the two lines with red font should be a single line and the whole section in grey should be 3 lines rather then 6. Specifically, it should be


Random Trait 1   (Method 1; Days) | Random Trait 2 (Method 2; Days) | Random Trait 3 (Method 3; Days) | Germplasm Name | Year | Location | Replicate
-- | -- | -- | -- | -- | -- | --
n/a | 25 | 119 | GERM0 | 2016 | Deles, Urgin | 1
n/a | 25 | 119 | GERM0 | 2016 | Deles, Urgin | 2
n/a | 25 | 119 | GERM0 | 2016 | Deles, Urgin | 3

**Review by laceysanderson — DISMISSED** [review]
This is still not working for me... Additionally now I see errors when I run the job...

```
$ drush trp-run-jobs --username=tripaladmin --root=/home/www/tripal2

2019-04-22 11:55:11
Tripal Job Launcher
Running as user '----'
-------------------
2019-04-22 11:55:11: There are 4 jobs queued.
2019-04-22 11:55:11: Job ID 69.
2019-04-22 11:55:11: Calling: tripal_tripal_cron_notification()
2019-04-22 11:55:20: Job ID 70.
2019-04-22 11:55:20: Calling: tripal_expire_collections()
2019-04-22 11:55:20: Job ID 71.
2019-04-22 11:55:20: Calling: tripal_expire_files()
2019-04-22 11:55:20: Job ID 72.
2019-04-22 11:55:20: Calling: analyzedphenotypes_trpdownload_generate_file(Array)
array_keys() expects parameter 1 to be array, null given analyzedphenotypes.module:1067                                                [warning]
array_keys() expects parameter 1 to be array, null given analyzedphenotypes.module:1067                                                [warning]
array_keys() expects parameter 1 to be array, null given analyzedphenotypes.module:1067                                                [warning]
array_keys() expects parameter 1 to be array, null given analyzedphenotypes.module:1067                                                [warning]
array_keys() expects parameter 1 to be array, null given analyzedphenotypes.module:1067                                                [warning]
array_keys() expects parameter 1 to be array, null given analyzedphenotypes.module:1067                                                [warning]
array_keys() expects parameter 1 to be array, null given analyzedphenotypes.module:1067                                                [warning]
array_keys() expects parameter 1 to be array, null given analyzedphenotypes.module:1067                                                [warning]
array_keys() expects parameter 1 to be array, null given analyzedphenotypes.module:1067                                                [warning]
array_keys() expects parameter 1 to be array, null given analyzedphenotypes.module:1067                                                [warning]
array_keys() expects parameter 1 to be array, null given analyzedphenotypes.module:1067                                                [warning]
```

and this is an excerpt from my file
```
"Random Trait 1 (Method 1; Days)"	"Random Trait 2 (Method 2; Days)"	"Random Trait 3 (Method 3; Days)"	"Germplasm Name"	Year	Location	Replicate
n/a	28	n/a	GERM0	2016	"Brusgow, Thikhland"	1
n/a	25	n/a	GERM0	2016	"Brusgow, Thikhland"	2
n/a	28	n/a	GERM0	2016	"Brusgow, Thikhland"	3
n/a	25	119	GERM0	2016	"Deles, Urgin"	1
n/a	25	n/a	GERM0	2016	"Deles, Urgin"	2
n/a	25	n/a	GERM0	2016	"Deles, Urgin"	3
n/a	n/a	119	GERM0	2016	"Deles, Urgin"	2
n/a	n/a	119	GERM0	2016	"Deles, Urgin"	3
11	n/a	n/a	GERM0	2016	"Durchester, Treheim"	1
8	n/a	n/a	GERM0	2016	"Durchester, Treheim"	2
11	n/a	n/a	GERM0	2016	"Durchester, Treheim"	3
n/a	60	n/a	GERM0	2016	"Durchester, Treheim"	1
n/a	60	47	GERM0	2016	"Durchester, Treheim"	2
n/a	60	n/a	GERM0	2016	"Durchester, Treheim"	3
n/a	n/a	47	GERM0	2016	"Durchester, Treheim"	1
n/a	n/a	46	GERM0	2016	"Durchester, Treheim"	3
```

**Comment by laceysanderson** [comment]
@reynoldtan the streamlined download code is now ready to test. I've removed the option to download non-averaged reps on the download form. There should now only be one row for each unique experiment-germplasm-location-year combination. This means there should be multiple traits shown on the same row of the file.

**Comment by laceysanderson** [comment]
PS. Also note #77 has already been reported and will be worked on separately.

**Comment by reynoldtan** [comment]
1. The update works for exported file as tsv and csv but when set to xlsx, the result does not contain the column header part.
Screen Shot 2019-05-01 at 10 15 49 AM


2. Result does not follow the order of headers selected. It is always in this order:
Traits, Germplasm Name, Year and Location.
Also, it excludes other optional header that you add to default headers (ie: country of origin, data collector).

**Comment by laceysanderson** [comment]
> Result does not follow the order of headers selected. It is always in this order:
> Traits, Germplasm Name, Year and Location.
> Also, it excludes other optional header that you add to default headers (ie: country of origin, data collector).

This is a separate bug and is evident on the master branch as well. It is documented in Issue #77.

**Comment by reynoldtan** [comment]
Header issue with xlsx type now fixed.

**Comment by Jiu9Shen** [comment]
I've picked germplsm randomly and downloaded its file for test. The test shows related rows (by experiment, germplasm, year and location) are merged into a single row properly.

**Comment by Jiu9Shen** [comment]
Although, the test revealed one concern of measurement with unit of days not being even number. For example, treat "Days till Plants have 1/2 of their Pods Mature" can be 155.5, 161.33 or 97.67 days now, which is not perfect.

**Review by Jiu9Shen — APPROVED** [review]
I've picked germplsm randomly and downloaded its file for test. The test shows related rows (by experiment, germplasm, year and location) are merged into a single row properly. Although, the test revealed one concern of measurements with unit of days not being even number. Please see issue #83 for details.

**Comment by laceysanderson** [comment]
Great, Thanks for the review!

**Pull request merged**
