### PR TITLE
NCIT Method Tripal WS Compatible

### PR DESCRIPTION
**Pull request by reynoldtan**
Field supports Tripal Web Services.

This PR made an update to hook_bundle_field_info() and to the field's elementInfo() and load().
The former will allow this field to support multiple values returned for both end user and Tripal Web Services by changing the cardinality settings, while the latter to alter the array structure and to define element definition.

## Metadata

 - Issue # https://github.com/UofS-Pulse-Binfo/analyzedphenotypes/issues/110 - Make NCIT:method Field Tripal Web Services Compatible

- [X] I feel this PR is ready to be merged.
- [X] This PR is dependent upon [PR #/ nothing]
    https://github.com/tripal/tripal/issues/1010 Web Services - Invalid Content Type
    in the meantime, just replace any occurrence of + (plus sign) in @id URL seen in the address field of your browser.

Documentation:
- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

## Testing?

1. Delete ncit__method if it is used in Trait content type.
2. Update ncit__method and analyzedphenotypes.field.inc
3. In the Trait Content Type, Click manage fields then Check for new fields.
4. Add ncit__method field to Trait Content type, Make sure to move this field out of disabled fields.
5. Access Traits Content Type in Tripal WS.

- [ ] I tested on a generic Tripal Site
- [X] I tested on a KnowPulse Clone
- [ ] This PR includes automated testing

### CODE REVIEW

**Review by laceysanderson — COMMENTED** [review]
So interestingly, if I use the URL to access the expanded method field it works perfectly:
Screen Shot 2019-10-30 at 3 53 28 PM

However, I do not see a link to expand the method field on the trait web services page???
Screen Shot 2019-10-30 at 3 53 13 PM
Despite it being clearly shown on the rendered page.
Screen Shot 2019-10-30 at 3 53 44 PM

I've cleared both my browser cache and the site cache multiple times as well as reloading the trait page...

**Comment by reynoldtan** [comment]
Interestingly enough, after you access the method through the url and go back to the method field the url to expand method now appears. Could this be cache issue? Looking at TWS for answers.

**Comment by reynoldtan** [comment]
We have caching issue, it is not just this method field but also with SIO:study field. I will demonstrate when you have time.

**Review by laceysanderson — APPROVED** [review]
Since the caching issue is universal and I've shown this PR to work, I'm merging 🎉

**Pull request merged**
